In [5]:
import heapq
import pandas as pd

# fake df
df = pd.DataFrame({
    'amount': [300, 250, 200, 50, 80],
    'deadline_date': ['2024-01-03', '2024-01-03', '2024-01-03', '2024-01-01', '2024-01-02']
})

In [6]:
# step 1 — convert dates to datetime
df['deadline_date'] = pd.to_datetime(df['deadline_date'])
df

   amount deadline_date
0     300    2024-01-03
1     250    2024-01-03
2     200    2024-01-03
3      50    2024-01-01
4      80    2024-01-02

In [7]:
# step 2 — convert dates to integer slots (earliest date = slot 1)
df['slot'] = df['deadline_date'].rank(method='dense').astype(int)
df

   amount deadline_date  slot
0     300    2024-01-03     3
1     250    2024-01-03     3
2     200    2024-01-03     3
3      50    2024-01-01     1
4      80    2024-01-02     2

In [13]:
# step 3 — sort by slot ascending
df = df.sort_values(['slot'])
df
#    amount deadline_date  slot
# 0      50    2024-01-01     1
# 1      80    2024-01-02     2
# 2     300    2024-01-03     3
# 3     250    2024-01-03     3
# 4     200    2024-01-03     3

   amount deadline_date  slot
3      50    2024-01-01     1
4      80    2024-01-02     2
0     300    2024-01-03     3
1     250    2024-01-03     3
2     200    2024-01-03     3

In [32]:
from collections import defaultdict

hi = defaultdict(list)
hi

defaultdict(list, {})

In [ ]:
pairs = [('Alice', 85), ('Bob', 92)]
hi= *pairs

In [18]:
# step 4 — convert to list of tuples
tasks = list(zip(df['amount'], df['slot']))
# [(50,1), (80,2), (300,3), (250,3), (200,3)]
tasks

[(50, 1), (80, 2), (300, 3), (250, 3), (200, 3)]

In [ ]:
# step 5 — run algorithm
def max_profit(tasks):
    heap = []
    for amount, deadline in tasks:
        heapq.heappush(heap, amount)
        if len(heap) > deadline:
            heapq.heappop(heap)  # evict least profitable
    return sum(heap), heap

total, selected = max_profit(tasks)
print(f"Max profit: {total}")   # 750
print(f"Selected amounts: {selected}")  # [200, 250, 300]

Max profit: 750
Selected amounts: [200, 250, 300]

In [7]:
int(-5/2)

-2

In [4]:
intervals = [[1,7],[1,6],[8,10],[15,18]]
intervals.sort()
intervals

[[1, 6], [1, 7], [8, 10], [15, 18]]

In [8]:
for i in range(2,5):
	print(i)

2
3
4

In [1]:
hi = list(range(20))
print(hi)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19]

In [9]:
nums = [8,1,2,2,3]
res = []
nums_sorted = sorted(nums)
for num in nums:
	res.append(nums.index(num))
print(res)

[0, 1, 2, 2, 4]

In [11]:
matrix = [[1,2,3],[4,5,6],[7,8,9]]
hi = matrix.pop(0)
print(hi)
print(matrix)

[1, 2, 3]
[[4, 5, 6], [7, 8, 9]]

In [5]:
def calculate_binary(s:str)->int:
        sum = 0
        pos = 0
        str_s = str(s)
        n = len(str_s)
        for x in range(n-1,-1,-1):
            sum+=(2^x)*int(str_s[pos])
            pos+=1
        return sum
hi = calculate_binary(1101)

In [1]:
for i in range(25, 2, -1):
    print(i, end=" ")
print()

25 24 23 22 21 20 19 18 17 16 15 14 13 12 11 10 9 8 7 6 5 4 3

In [10]:
hi = {
	'hi':1,
	'bye':2,
	'idsafasd':3
}
1 in hi.values()

True

In [17]:
blah = set()
blah.add(1)
blah.add(2)
blah.add(1)
1 in blah

True

In [13]:
arr1 = [1,3]
arr2 = [2,4]
arr3 = arr1+arr2
arr3 = sorted(arr3)
arr3

[1, 2, 3, 4]

In [2]:
words = ["apple", "banana", "cherry", "date"]
sorted_by_len = sorted(words,key=len)
sorted_by_len

['date', 'apple', 'banana', 'cherry']

In [3]:
"cat" in "cattle"

True